### ISSUE TITLE
User signup form validation

### ISSUE THREAD

**Issue by esteban-gs** [Nonprofit-Exchange-Hub/web-app#290]
User sign up form should validate accept terms, email, zip and provide useful validation errors to the user for each of those fields.

This will require using a form library (see UserOrg sign up form) as well as a multi-step verification form (when the user can go to the next step)

Blocked by:
- https://github.com/Nonprofit-Exchange-Hub/web-app/issues/287
- https://github.com/Nonprofit-Exchange-Hub/web-app/issues/286
- https://github.com/Nonprofit-Exchange-Hub/web-app/issues/288

**Comment by yulejessica** [comment]
- Two signup forms and only worry about the **User Signup Form**
- Need to work on adding inputs(for example, the password is not meeting the length requirement) validation for the signup form and ensure not to send fetch requests if the form's input is not validated. 

- the file of the form is here : 
Main component client/src/views/SignupCitizen.tsx

- org sign-up form, which is a good example: client/src/components/Users/Auth/SignUpUserAndNonprofit/SignUpUserAndNonprofit.tsx
- here’s where a lot of the logic for validating lives 
client/src/components/Users/Auth/SignUpUserAndNonprofit/validation-rules.ts

Let's work with Esteban since he wrote the code for the user signup form.

**Comment by esteban-gs** [comment]
> 

Thanks, @yulejessica . A lot of this work depends on using the [`react-hooks-form` library](https://react-hook-form.com/) as well as [`yup`](https://github.com/jquense/yup). These are not that simple to work with. If you know of alternatives, it's always welcome.

**Comment by yulejessica** [comment]
Hey @esteban-gs, I am just starting to work on this and I was hoping if we could get together sometime this week to go over your code in client/src/components/Users/Auth/SignUpUserAndNonprofit/SignUpUserAndNonprofit.tsx 
I can do it this Tuesday or Thursday night. LMK :)
