### ISSUE TITLE
sign in modal

### ISSUE THREAD

**Issue by jd2rogers2** [Nonprofit-Exchange-Hub/web-app#306]
get rid of the old sign up page
make a modal like the figmas here
keep all of the old sign in functionality
this modal should overlay over any page, so render the component outside of the Main component in App.tsx
https://www.figma.com/file/K7DT5jYcLKRc9epmNrO0N7/UX---Dev-Handoff?node-id=109-5812&t=0a5133SJk6atcWfw-0

May want to look at creating another global context to toggle on-off. It can AppContext

**Comment by EtoKruto** [comment]
branch [ 306-sign-in-modal](https://github.com/Nonprofit-Exchange-Hub/web-app/pull/329) was giving me a lot of trouble setting up environment so I branched from current main  into [306-sign-in-and-modal-new](https://github.com/Nonprofit-Exchange-Hub/web-app/tree/306-sign-in-and-modal-new) and was able to set everything up. Worked on the modal there.

At this point, the functionality is there, but the handleClickOutisde is giving trouble and not working correctly and I left the console log to show what happens when clicking **modalRef.current** and **even.target** within the same function using Ref. The visual css isn't fully complete but 80-90% there. 

@denniswangcodes feel free to create the SignUp page using the style created in the Modal.tsx so the modals look similar

**Comment by esteban-gs** [comment]
@EtoKruto , since you had to create a new branch, let's close this PR and start a new one on your new branch and reference this one there.

**Comment by EtoKruto** [comment]
New RP - https://github.com/Nonprofit-Exchange-Hub/web-app/pull/351

**Comment by marvinsjsu** [comment]
Hi @EtoKruto, looks like your PR#351 was approved by Esteban.  I'm gonna move this ticket to "In-Review" for now.  Please feel free to move it to "Done" once you've merged it.  Thanks!
