### ISSUE TITLE
Clean up lint warnings in /server

### ISSUE THREAD

**Issue by marvinsjsu** [Nonprofit-Exchange-Hub/web-app#356]
We have numerous unused imports in `/server`.  These generate warnings that can be noisy.  Let's clean this up by removing the lines importing unused packages or modules.

Warnings we get when running `npm run lint`:

![Image](https://user-images.githubusercontent.com/2562488/254433921-452248c5-8d68-4869-bde1-7e9dbb7dfd2e.png)

**Comment by junsupark94** [comment]
I checked it out and it seems to be due to the installed Typescript version 4.9.5 not being supported by typescript-eslint. Because these modules are being used.

![Image](https://github.com/Nonprofit-Exchange-Hub/web-app/assets/97586064/35528095-c02b-4da5-a646-117fe5f193ee)

![Image](https://github.com/Nonprofit-Exchange-Hub/web-app/assets/97586064/1659bfe3-8779-4882-a4cb-9007e4db59a5)

I tried updating the library and the error messages are reduced from 200+ to about 10. Should I go ahead with this fix?

**Comment by marvinsjsu** [comment]
@junsupark94, if you're comfortable with the update and don't see any regressions, then yea let's do it.  Thanks for taking a closer look at this.  

Also, if possible, can we look into the remaining 10 warnings - feel free to create tickets if any of these require additional research/investigation.

**Comment by junsupark94** [comment]
@marvinsjsu I can fix this by updating just **@typescript-eslint/parser** to the _@latest_ or by updating that and **@typescript-eslint/eslint-plugin** and **eslint** to the _@latest_ too.


![Image](https://github.com/Nonprofit-Exchange-Hub/web-app/assets/97586064/9e603ef4-288d-4035-90c7-331f9c534122)


![Image](https://github.com/Nonprofit-Exchange-Hub/web-app/assets/97586064/ac4161f0-9a6d-4173-af30-2ebff64863d8)

Updating just the parser shows the remaining 11 problems as warnings.

![Image](https://github.com/Nonprofit-Exchange-Hub/web-app/assets/97586064/6b3c9769-98a1-468e-84b8-67b369e0acd6)

Updating all three shows the remaining 11 problems as errors.

![Image](https://github.com/Nonprofit-Exchange-Hub/web-app/assets/97586064/161f8e19-41b7-4f87-910d-442ea82eacc2)

Let me know how you'd like to proceed. Also, the problems where it says _'args' is defined but never used_ in **interests.validator.ts,** I think I should leave them alone since this file seems incomplete. The other problems are just unused imports which shouldn't be a problem to get rid of. Let me know if you'd like the args removed as well.

![Image](https://github.com/Nonprofit-Exchange-Hub/web-app/assets/97586064/c6b2448e-28fd-41a1-8a87-4fe88506aba8)

**Comment by marvinsjsu** [comment]
My preference is to have warnings instead of errors for these unused references and I also agree with leaving the `args` as is for now.  That said, I think we can go go with whichever option you choose (updating just the parser or the latter).  Thanks for figuring out what's causing these warning messages.
